import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Quien es un Líder Regional",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-que-es-un-lider-regional-podcast-1.mp3",
            active: true,
        },
        {
            name:"Que es ser Voluntario a tiempo completo en el Movimiento Tengo Sed",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-que-es-ser-voluntario-a-tiempo-completo-en-el-movimiento-tengo-sed-1.mp3",
            active: false,
        },
        {
            name:"Comunidades Juveniles en el MTS PRIMERA PARTE",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-comunidades-juveniles-en-el-mts-primera-parte-1.mp3",
            active: false,
        },
        {
            name:"Comunidades Juveniles en el MTS SEGUNDA PARTE",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-comunidades-juveniles-en-el-mts-segunda-parte-1.mp3",
            active: false,
        },
        {
            name:"Comunidades Juveniles en el MTS TERCERA PARTE",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-comunidades-juveniles-en-el-mts-tercera-parte-1.mp3",
            active: false,
        },
        {
            name:"Quien es un Oblato en el Movimiento Tengo Sed",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-quien-es-un-oblato-en-el-movimiento-tengo-sed.-1-1.mp3",
            active: false,
        },
        {
            name:"Desafíos en la vida comunitaria en el MTS",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-desafios-en-la-vida-comunitaria-en-el-mts-podcast-1.mp3",
            active: false,
        },
        {
            name:"EL anhelo de Dios de amar y ser amado",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-el-anhelo-de-dios-de-amar-y-ser-amado-por-padre-curtis-mc-1.mp3",
            active: false,
        },
        {
            name:"Caminando con María",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-caminando-con-maria-1.mp3",
            active: false,
        },
        {
            name:" El Legado de Madre Teresa al MTS",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-el-legado-de-madre-teresa-al-mts-1.mp3",
            active: false,
        },
        {
            name:"El MTS y su relacion con la Iglesia",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-el-mts-y-su-relacion-con-la-iglesia.mp3",
            active: false,
        },
        {
            name:"La Sed y el Sagrado Corazón de Jesús",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/11/la-sed-y-el-sagrado-corazon-de-jesus.mp3",
            active: false,
        },
        {
            name:"La Vocacion y la respuesta de Madre a su Vocacion PARTE 1",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/12/la-vocacion-y-respuesta-de-la-madre-a-su-vocacion-pt-1.mp3",
            active: false,
        },
        {
            name:"La Vocacion y la respuesta de Madre a su Vocacion PARTE 2",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://musiczoneapps.files.wordpress.com/2022/12/la-vocacion-y-respuesta-de-la-madre-a-su-vocacion-pt-2.mp3",
            active: false,
        },
        {
            name:"Como acompañar Comunidades en el MTS",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://musiczoneapps.files.wordpress.com/2023/01/14.-podcast-como-acompanar-comunidades-en-el-mts.mp3",
            active: false,
        },
        {
            name:"La Vocacion y la respuesta de Madre a su Vocacion PARTE 3",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://musiczoneapps.files.wordpress.com/2023/01/15.-podcast-la-vocacion-y-respuesta-de-la-madre-teresa-a-su-vocacion-parte-3.mp3",
            active: false,
        },
        {
            name:"Desafios en el MTS",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://musiczoneapps.files.wordpress.com/2023/02/16.-podcast-desafios-en-el-mts.mp3",
            active: false,
        },
        {
            name:"Liderazgo desde cero",
            artist: "Facebook Live",
            cover: "https://musiczoneapps.files.wordpress.com/2022/10/podcast-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://musiczoneapps.files.wordpress.com/2023/05/17.-liderazgo-desde-cero-podcast.mp3",
            active: false,
        },
    ];
}

export default chillHop;

